name: Scheduled Job

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scheduled-run:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduled run message
        run: echo "Yeh workflow roz midnight pe chalta hai!"
